baseURL = "http://example.org/"
languageCode = "en-us"
title = "Sven"
theme = "autophugo"

[Author]
    name = "Sven"

[params]
    # Meta
    description = "Sven - The 1985 El Camino"
    keywords = "sven, chevy, el camino"
    #msvalidate = ""
    #googlesiteverification = ""
    #thumb_width = 480
    #thumb_quality = 50
    #full_width = 960
    #full_quality = 90
    #column_count = 2
    #breadcrumb_use_title = false
    #filename_as_phototitle = false
    #images_downloadable = true
    
    # Headerbar links
    # Do not put too many links here,
    # it will break mobile appearance

    [[params.header.links]]
    name = "About"
    url = "#footer"
    icon = "fa-info-circle"    
    
    # Footer panel
    
    [params.footer.paragraph]
    headline = "Sven the 1985 El Camino"
    text = "Sven is one of only about 2200 Choo Choo Customs El Caminos."
    
    # [params.footer.social]
    # headline = "Follow me"

    # [[params.footer.social.links]]
    # label = "Twitter"
    # url = "#"
    # icon = "fa-twitter"
 
    # [[params.footer.social.links]]
    # label = "Facebook"
    # url = "#"
    # icon = "fa-facebook"
 
    # [[params.footer.social.links]]
    # label = "Instagram"
    # url = "#"
    # icon = "fa-instagram"

    # [[params.footer.social.links]]
    # label = "Github"
    # url = "#"
    # icon = "fa-github"

    # [[params.footer.social.links]]
    # label = "LinkedIn"
    # url = "#"
    # icon = "fa-linkedin"
    
    # Contact form
    
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'realEmail' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    
    [params.footer.contact]
    hide = true # Set this to true if you don't want to have a contact form on your site
    # realEmail = "example@example.org"
    # headline = "Get in touch"
    # buttonText = "Send"
    # resetText = "Reset"
    
    # # 'warning' defines error messages for invalid inputs
    # [params.footer.contact.name]
    # text = "Name *"
    # warning = "Please, enter your name"

    # [params.footer.contact.email]
    # text = "Email *"
    # warning = "Please, enter your email."

    # [params.footer.contact.message]
    # text = "Message *"
    # warning = "Please, enter your message"
    
    # Copyright
    [params.footer.copyright]
    name = "Allison Tharp"
